#! /bin/sh

# Colors
. "${HOME}/.cache/wal/colors.sh"

# Killing any possible previous processes
killall -q -w picom
killall -q -w sxhkd
killall -q -w polybar

sxhkd &
picom &
dunst &
polybar -c=~/.config/polybar/bar mybar -r &
nitrogen --restore &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7

# Mouse configs
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer	true

# Settings
bspc config focused_border_color    "$color15"  
bspc config normal_border_color     "$color0"

bspc config top_padding         20
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
